### ISSUE TITLE
Scilis returns `character(0)` if cookie value has a dot

### ISSUE THREAD

**Issue by kennedymwavu** [ambiorix-web/scilis#1]
This is more of an enquiry. Scilis returns `character(0)` if cookie value has a dot. This happens because `scilis::unsign()` uses a dot as the value to split on. See [here](https://github.com/devOpifex/scilis/blob/2ceb1a2eb5c3dbb3c0bbc180556fc2dfb4020b4c/R/middleware.R#L81).

Is this the expected behaviour?

Here is a reprex:

```r
library(scilis)
library(ambiorix)

port <- 5500
host <- "127.0.0.1"

app <- Ambiorix$new(host = host, port = port)

app$use(scilis("secret"))

app$get("/", \(req, res) {
  print(req$cookie)
  res$cookie(
    "MYCOOKIE",
    "mwavu.me"
  )
  res$send("Added cookie")
})

app$start()
```

**Comment by kennedymwavu** [comment]
Upon looking at `scilis::sign()`, I believe that's the expected behaviour since it also uses a dot to concatenate the cookie value and the hash. See [here](https://github.com/devOpifex/scilis/blob/2ceb1a2eb5c3dbb3c0bbc180556fc2dfb4020b4c/R/middleware.R#L75).

Maybe adding this as a note in the docs would be useful?

**Comment by JohnCoene** [comment]
That's more of a bug, should change how scilis does things to allow for dots.

Well spotted this!

**Comment by JohnCoene** [comment]
We have to change `.` for something else unlikely to be used I guess, e.g.: `|.|` then we can split with `strsplit(..., "\\|\\.\\|")`?

**Comment by kennedymwavu** [comment]
How about using `devOpifex/scilis` as the string to split on? It is unlikely to be used and you don't have to escape any characters.

**Comment by kennedymwavu** [comment]
I'd be glad to make a PR. You can assign the issue to me.
