### ISSUE TITLE
From base64enc to b64

### ISSUE THREAD

**Issue by jrosell** [ambiorix-web/scilis#5]
I would like to use b64 instead of base64enc... Or maybe be able to use one or another.

Is it ok if I do a PR?

**Comment by JohnCoene** [comment]
Of course, looking forward!

**Comment by jrosell** [comment]
I close it, because I see that it could make depends on rustc :/

**Comment by JohnCoene** [comment]
But that is fine with extendr right?

**Comment by jrosell** [comment]
Yes, but adding it as "suggest" made rustc as required and maybe will be more complex to publish it into cran someday.

**Comment by JohnCoene** [comment]
As you want but it's fine by me to be honest, I don't see CRAN as mandatory, your call
